image: Visual Studio 2019


build_script:
 - cmd: cd solver_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target solver
 - cmd: echo "Testing solver is done"
